import Head from "next/head";
import { Text, Flex, Button, Icon, Input } from "@chakra-ui/react";
import HomePageHeader from "@/Components/Headers/HomePage.Header";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth, firestore } from "@/Components/Firebase/ClientApp";
import ContentLayout from "@/Components/Layout/Content.Layout";
import HomeRHS from "@/Components/LeftContentComponent/HomeSideContent/HomeRHS";
import PostCard from "@/Components/Card/PostCard";
import HomeLHS from "@/Components/LeftContentComponent/HomeSideContent/HomeLHS";
import HomeNavFooter from "@/Components/MobileFooter/HomeNavFooter";
import { CiCirclePlus, CiSearch } from "react-icons/ci";
import Link from "next/link";
import { SearchIcon } from "@/Components/Icons/Icons";
import { collection, doc, getDocs } from "firebase/firestore";
import { useEffect, useState } from "react";
import { Draft } from "@/Hooks/Blog/useCreateNewArticle";
import { ArticleLoaders } from "@/Components/Loaders/loader";

export default function Home() {
  const [user] = useAuthState(auth);
  const [articleList, setArticleList] = useState<Draft[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchHomeArticle = async () => {
    setLoading(true);
    const querrySnapshot = await getDocs(
      collection(firestore, "users", "@eb3rechi", "drafts")
    );
    const articles = querrySnapshot.docs.map((doc) => ({
      ...doc.data(),
    }));
    setArticleList(articles as Draft[]);
    setLoading(false);
  };

  useEffect(() => {
    if (articleList) {
      fetchHomeArticle();
      return;
    }
    console.log("i ran");
  }, [user]);
  return (
    <>
      <Head>
        <title>Ooyinye</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <HomePageHeader />}

      <main>
        <ContentLayout>
          <>
            <HomeRHS />
          </>
          <>
            <HomeNavFooter />
            <Flex flexDir={"column"} width={"100%"}>
              <Text width={"100%"} fontWeight={"900"} px={"4"}>
                Top Reads
              </Text>
              {loading && (
                <>
                  <ArticleLoaders />
                  <ArticleLoaders />
                  <ArticleLoaders />
                  <ArticleLoaders />
                </>
              )}
              {!loading &&
                articleList.map((article, index) => (
                  <Flex key={index}>
                    <PostCard
                      id={index}
                      articleSlug={article.articleSlug}
                      articleTitle={article.articleTitle}
                      articleContent={article.articleContent}
                      articleThumbnail={article.articleThumbnail}
                      articleDesc={article.articleDesc}
                      showProfile={true}
                    />
                  </Flex>
                ))}
            </Flex>

            <Flex width={"100%"} flexDir={"column"} py={"20"}>
              <Flex
                width={"100%"}
                justify={"space-between"}
                align={"center"}
                px={"4"}
              >
                <Text fontWeight={"900"}>For you</Text>
                <Link href={"/search"}>
                  <Flex
                    align={"center"}
                    borderRadius={"full"}
                    border={"1px solid"}
                    borderColor={"gray.300"}
                    p={{
                      base: "1",
                      md: "0",
                    }}
                    px={{ md: "2" }}
                  >
                    <SearchIcon value="" />
                    <Input
                      placeholder="search blog"
                      border={"none"}
                      disabled
                      display={{ base: "none", md: "unset" }}
                    />
                  </Flex>
                </Link>
              </Flex>

              {/* {loading && (
                <>
                  <ArticleLoaders />
                  <ArticleLoaders />
                  <ArticleLoaders />
                  <ArticleLoaders />
                </>
              )}
              {!loading &&
                articleList.map((article, index) => (
                  <PostCard
                    id={index}
                    articleSlug={article.articleSlug}
                    articleTitle={article.articleTitle}
                    articleContent={article.articleContent}
                    articleThumbnail={article.articleThumbnail}
                    articleDesc={article.articleDesc}
                    showProfile={true}
                  />
                ))} */}
            </Flex>
          </>
          <>
            <HomeLHS />
          </>
        </ContentLayout>
      </main>
    </>
  );
}
